project_id = "gifzytiilztglnvescqg"

[functions.ask-specter]
verify_jwt = false

[functions.seo-analysis]
verify_jwt = false

[functions.intelligence-feed]
verify_jwt = false

[functions.social-scheduler]
verify_jwt = false

[functions.operational-mode]
verify_jwt = false

[functions.warm-lead-seizure]
verify_jwt = true

[functions.test-warm-seizure]
verify_jwt = false

[functions.lead-threat-scoring]
verify_jwt = true
