-- Add dummy data for Calendar (appointments)
INSERT INTO public.appointments (title, description, start_time, end_time, location, meeting_link, status, contact_id) VALUES
('Sales Call - Acme Corp', 'Follow-up call with John Smith regarding enterprise license proposal', '2024-07-18 10:00:00+00', '2024-07-18 11:00:00+00', 'Virtual Meeting', 'https://meet.google.com/abc-def-ghi', 'scheduled', (SELECT id FROM contacts WHERE email = 'john.smith@acmecorp.com')),
('Demo Session - TechStart', 'Product demonstration for Sarah Johnson and team', '2024-07-19 14:00:00+00', '2024-07-19 15:30:00+00', 'Client Office', 'https://zoom.us/j/123456789', 'scheduled', (SELECT id FROM contacts WHERE email = 'sarah.j@techstart.io')),
('Contract Review - GlobalTech', 'Final contract discussion with Mike Chen', '2024-07-22 09:00:00+00', '2024-07-22 10:00:00+00', 'Conference Room A', NULL, 'scheduled', (SELECT id FROM contacts WHERE email = 'mike.chen@globaltech.com')),
('Product Training - Innovate Labs', 'Onboarding session for Emma Williams team', '2024-07-25 13:00:00+00', '2024-07-25 16:00:00+00', 'Client Site', NULL, 'scheduled', (SELECT id FROM contacts WHERE email = 'e.williams@innovate.com')),
('Quarterly Business Review', 'Q2 performance review with Enterprise Solutions', '2024-07-30 11:00:00+00', '2024-07-30 12:30:00+00', 'Virtual Meeting', 'https://teams.microsoft.com/xyz', 'completed', (SELECT id FROM contacts WHERE email = 'j.taylor@enterprise.com')),
('Initial Consultation - Future Startup', 'Discovery call with David Brown', '2024-08-01 15:00:00+00', '2024-08-01 16:00:00+00', 'Virtual Meeting', 'https://meet.google.com/startup-call', 'scheduled', (SELECT id FROM contacts WHERE email = 'david@startup.co')),
('Technical Deep Dive - MegaCorp', 'Architecture discussion with Lisa Davis', '2024-08-05 10:00:00+00', '2024-08-05 12:00:00+00', 'Client Office', NULL, 'scheduled', (SELECT id FROM contacts WHERE email = 'lisa.davis@megacorp.com')),
('Implementation Planning - ScaleUp', 'Project kickoff with Robert Wilson', '2024-08-08 14:00:00+00', '2024-08-08 15:30:00+00', 'Virtual Meeting', 'https://zoom.us/j/scaleup123', 'scheduled', (SELECT id FROM contacts WHERE email = 'r.wilson@scaleup.com'));

-- Add dummy data for Social Media (social_posts)
INSERT INTO public.social_posts (platform, content, status, scheduled_at, published_at, engagement_metrics, media_urls) VALUES
('LinkedIn', 'Excited to announce our Q2 growth of 150%! Our enterprise solutions are helping companies scale faster than ever. #Growth #Enterprise #SaaS', 'published', '2024-07-15 09:00:00+00', '2024-07-15 09:00:00+00', '{"likes": 245, "comments": 18, "shares": 32, "impressions": 3450}', '{"https://example.com/growth-chart.jpg"}'),
('Twitter', 'Just closed another major deal! Our sales team is on fire 🔥 Thank you to all our amazing clients for trusting us with their business growth. #Sales #Success', 'published', '2024-07-16 14:30:00+00', '2024-07-16 14:30:00+00', '{"likes": 89, "retweets": 23, "comments": 12, "impressions": 1250}', NULL),
('LinkedIn', 'Customer spotlight: See how @TechStart increased their productivity by 200% using our platform. Case study in comments 👇 #CustomerSuccess #Productivity', 'published', '2024-07-10 11:00:00+00', '2024-07-10 11:00:00+00', '{"likes": 312, "comments": 45, "shares": 67, "impressions": 4200}', '{"https://example.com/techstart-case-study.pdf"}'),
('Twitter', 'New feature alert! 🚨 Real-time analytics dashboard is now live. Get instant insights into your business performance. Try it free ➡️ link.com/analytics', 'published', '2024-07-12 16:00:00+00', '2024-07-12 16:00:00+00', '{"likes": 156, "retweets": 34, "comments": 8, "impressions": 2100}', '{"https://example.com/analytics-demo.gif"}'),
('LinkedIn', 'Webinar announcement: "Scaling Your Business with AI-Powered Analytics" - July 25th, 2PM EST. Industry experts will share actionable insights. Register now!', 'scheduled', '2024-07-20 10:00:00+00', NULL, NULL, NULL),
('Twitter', 'Monday motivation: "Success is not final, failure is not fatal: it is the courage to continue that counts." - Winston Churchill. Keep pushing forward! 💪', 'scheduled', '2024-07-22 08:00:00+00', NULL, NULL, NULL),
('LinkedIn', 'Behind the scenes: Our development team working on the next game-changing feature. Can you guess what it is? 🤔 #Innovation #Development', 'draft', NULL, NULL, NULL, '{"https://example.com/dev-team.jpg"}'),
('Twitter', 'Flash sale! 50% off all annual plans for the next 48 hours. Use code: SUMMER50. Limited time offer! ⏰ #Sale #LimitedOffer', 'draft', NULL, NULL, NULL, NULL);

-- Add dummy data for Email Marketing (email_templates first, then campaigns)
INSERT INTO public.email_templates (name, subject, content, template_type, is_active) VALUES
('Welcome Series - Day 1', 'Welcome to [Company Name]! Let''s get you started', 'Hi {{first_name}},\n\nWelcome to our platform! We''re excited to have you on board.\n\nHere''s what you can expect in the next few days:\n- Complete setup guide\n- Best practices tutorial\n- 1-on-1 onboarding call\n\nBest regards,\nThe Team', 'onboarding', true),
('Product Demo Follow-up', 'Thanks for attending our demo - Next steps', 'Hi {{first_name}},\n\nThank you for taking the time to see our product demo today.\n\nAs discussed, here are the next steps:\n1. Free trial access (expires in 14 days)\n2. Schedule implementation call\n3. Review pricing options\n\nLet me know if you have any questions!\n\nBest,\n{{sender_name}}', 'follow_up', true),
('Monthly Newsletter', 'Your monthly business insights - {{month}} {{year}}', 'Hi {{first_name}},\n\nHere''s your monthly roundup of business insights:\n\n• Industry trends and analysis\n• Customer success stories\n• Product updates and new features\n• Upcoming events and webinars\n\nRead the full newsletter →\n\nBest regards,\nThe Marketing Team', 'newsletter', true),
('Proposal Follow-up', 'Following up on your proposal - {{company_name}}', 'Hi {{first_name}},\n\nI wanted to follow up on the proposal we sent last week for {{company_name}}.\n\nQuick recap:\n- Implementation timeline: 4-6 weeks\n- Investment: {{proposal_amount}}\n- ROI projection: {{roi_projection}}\n\nDo you have any questions about the proposal?\n\nBest,\n{{sender_name}}', 'follow_up', true);

INSERT INTO public.email_campaigns (name, subject, content, template_id, status, recipient_count, sent_count, opened_count, clicked_count, scheduled_at, sent_at) VALUES
('Q2 Newsletter Campaign', 'Your Q2 business insights are here!', 'Quarterly insights and updates for our valued customers', (SELECT id FROM email_templates WHERE name = 'Monthly Newsletter'), 'sent', 1250, 1248, 856, 234, '2024-07-01 10:00:00+00', '2024-07-01 10:00:00+00'),
('Welcome Series - New Signups', 'Welcome to the future of business intelligence!', 'Onboarding sequence for new trial users', (SELECT id FROM email_templates WHERE name = 'Welcome Series - Day 1'), 'sent', 89, 89, 76, 45, '2024-07-15 09:00:00+00', '2024-07-15 09:00:00+00'),
('Demo Follow-up Campaign', 'Thanks for your interest - let''s continue the conversation', 'Following up with demo attendees from last week', (SELECT id FROM email_templates WHERE name = 'Product Demo Follow-up'), 'sent', 34, 34, 28, 12, '2024-07-10 14:00:00+00', '2024-07-10 14:00:00+00'),
('Proposal Follow-up - Enterprise Leads', 'Don''t miss out on this opportunity', 'Following up on outstanding proposals', (SELECT id FROM email_templates WHERE name = 'Proposal Follow-up'), 'scheduled', 15, 0, 0, 0, '2024-07-25 11:00:00+00', NULL),
('Product Update Announcement', 'New features that will transform your workflow', 'Announcing new analytics dashboard and reporting features', NULL, 'draft', 0, 0, 0, 0, NULL, NULL),
('Webinar Invitation', 'Free webinar: Scale your business with AI analytics', 'Invitation to upcoming webinar on AI-powered business insights', NULL, 'scheduled', 500, 0, 0, 0, '2024-07-20 08:00:00+00', NULL);

-- Add dummy data for Task Manager (tasks)
INSERT INTO public.tasks (title, description, status, priority, due_date, contact_id, deal_id) VALUES
('Follow up on Acme Corp proposal', 'Send contract revisions and schedule final review meeting', 'pending', 'high', '2024-07-20 17:00:00+00', (SELECT id FROM contacts WHERE email = 'john.smith@acmecorp.com'), (SELECT id FROM deals WHERE title = 'Acme Corp - Enterprise License')),
('Prepare TechStart demo materials', 'Customize demo environment with TechStart branding and use cases', 'in_progress', 'high', '2024-07-19 12:00:00+00', (SELECT id FROM contacts WHERE email = 'sarah.j@techstart.io'), (SELECT id FROM deals WHERE title = 'TechStart - Startup Package')),
('Send GlobalTech integration specs', 'Compile technical requirements document for API integration', 'completed', 'medium', '2024-07-18 16:00:00+00', (SELECT id FROM contacts WHERE email = 'mike.chen@globaltech.com'), (SELECT id FROM deals WHERE title = 'GlobalTech - Integration Project')),
('Schedule Innovate Labs training', 'Coordinate with their team for product training sessions', 'pending', 'medium', '2024-07-25 10:00:00+00', (SELECT id FROM contacts WHERE email = 'e.williams@innovate.com'), (SELECT id FROM deals WHERE title = 'Innovate Labs - Product Suite')),
('Update CRM with Enterprise Solutions outcome', 'Record meeting notes and next steps from QBR', 'completed', 'low', '2024-07-16 18:00:00+00', (SELECT id FROM contacts WHERE email = 'j.taylor@enterprise.com'), (SELECT id FROM deals WHERE title = 'Enterprise - Complete Solution')),
('Create Future Startup proposal', 'Draft customized proposal based on discovery call insights', 'in_progress', 'medium', '2024-08-02 17:00:00+00', (SELECT id FROM contacts WHERE email = 'david@startup.co'), (SELECT id FROM deals WHERE title = 'Future Startup - Growth Plan')),
('Prepare MegaCorp technical presentation', 'Create architecture slides for technical deep dive meeting', 'pending', 'high', '2024-08-05 09:00:00+00', (SELECT id FROM contacts WHERE email = 'lisa.davis@megacorp.com'), (SELECT id FROM deals WHERE title = 'MegaCorp - Department License')),
('ScaleUp implementation kickoff prep', 'Prepare project timeline and resource allocation plan', 'pending', 'medium', '2024-08-08 12:00:00+00', (SELECT id FROM contacts WHERE email = 'r.wilson@scaleup.com'), (SELECT id FROM deals WHERE title = 'ScaleUp - Multi-Year Contract')),
('Q3 pipeline review', 'Analyze current pipeline and forecast for next quarter', 'pending', 'high', '2024-07-31 17:00:00+00', NULL, NULL),
('Update sales playbook', 'Incorporate lessons learned from recent deals', 'in_progress', 'low', '2024-08-15 17:00:00+00', NULL, NULL),
('Competitive analysis research', 'Research latest competitor offerings and pricing', 'pending', 'medium', '2024-08-10 17:00:00+00', NULL, NULL),
('Customer testimonial collection', 'Reach out to satisfied customers for case studies', 'pending', 'low', '2024-08-20 17:00:00+00', NULL, NULL);