-- Insert demo tasks using proper UUID
INSERT INTO tasks (title, description, priority, status, due_date, user_id) VALUES
('Follow up with TechCorp lead', 'Contact the decision maker from TechCorp to discuss their pain points with current solution', 'high', 'pending', '2024-07-20 10:00:00'::timestamp, gen_random_uuid()),
('Research DataSolutions pricing strategy', 'Analyze competitor pricing model and find opportunities for aggressive undercutting', 'medium', 'in_progress', '2024-07-18 14:00:00'::timestamp, gen_random_uuid()),
('Schedule LinkedIn campaign against CloudInnovate', 'Launch targeted social media campaign highlighting their recent security breach', 'high', 'pending', '2024-07-17 09:00:00'::timestamp, gen_random_uuid()),
('Update competitive analysis report', 'Refresh Q3 intelligence report with latest market share data and sentiment analysis', 'medium', 'in_progress', '2024-07-22 16:00:00'::timestamp, gen_random_uuid()),
('Review StartupX funding announcement', 'Analyze their Series B funding and implications for our market position', 'high', 'completed', '2024-07-15 11:00:00'::timestamp, gen_random_uuid()),
('Prepare disruption campaign for WebCorp', 'Create content strategy to expose their customer service issues', 'medium', 'pending', '2024-07-25 13:00:00'::timestamp, gen_random_uuid()),
('Monitor competitor ad spend', 'Track advertising investments across all major platforms', 'low', 'in_progress', '2024-07-19 08:00:00'::timestamp, gen_random_uuid()),
('SEO attack on competitor keywords', 'Target high-value keywords currently dominated by TechCorp', 'high', 'completed', '2024-07-14 15:00:00'::timestamp, gen_random_uuid()),
('Customer sentiment analysis', 'Deep dive into competitor customer reviews and social mentions', 'medium', 'pending', '2024-07-21 12:00:00'::timestamp, gen_random_uuid()),
('Prepare whisper campaign materials', 'Create anonymous content highlighting competitor weaknesses', 'high', 'in_progress', '2024-07-18 10:00:00'::timestamp, gen_random_uuid());

-- Insert demo email templates  
INSERT INTO email_templates (name, subject, content, template_type, user_id) VALUES
('Competitive Intelligence Alert', 'Market Opportunity: {competitor_name} Vulnerability Detected', 'Dear Team,\n\nOur AI surveillance systems have identified a critical vulnerability in {competitor_name}''s market position:\n\n{vulnerability_details}\n\nRecommended Actions:\n- Immediate price adjustment to capitalize\n- Targeted social media campaign\n- Customer acquisition push\n\nTime-sensitive opportunity. Deploy within 24 hours.\n\nRegards,\nSpecter Net Intelligence', 'intelligence', gen_random_uuid()),
('Stealth Campaign Launch', 'Operation {campaign_code}: Deployment Authorized', 'Operative,\n\nYour stealth mission against {target_company} is now active.\n\nObjective: {mission_objective}\nDuration: {campaign_duration}\nSuccess Metrics: {success_criteria}\n\nMaintain operational security. Report status every 48 hours.\n\nThis message will self-destruct in 10 seconds... (just kidding)\n\nCommand Center', 'campaign', gen_random_uuid()),
('Customer Acquisition', 'Exclusive Offer: Switch from {competitor_name} and Save 40%', 'Hi {customer_name},\n\nTired of {competitor_name}''s limitations? Our intelligence shows you''re not alone.\n\nSpecial Migration Offer:\n✓ 40% off first year\n✓ Free data migration\n✓ Dedicated success manager\n✓ 24/7 premium support\n\nOver 500 companies have already made the switch this quarter.\n\nReady to upgrade? Book a demo: {demo_link}\n\nBest regards,\n{agent_name}', 'sales', gen_random_uuid()),
('Market Disruption Notice', 'Industry Alert: {disruption_event}', 'Industry Leaders,\n\nA significant market disruption has been detected:\n\n{disruption_details}\n\nImpact Analysis:\n- Market share redistribution likely\n- Customer behavior patterns shifting\n- Pricing pressure expected\n\nStrategic Response Plan:\n{response_strategy}\n\nNext Review: {next_review_date}\n\nStay vigilant,\nMarket Intelligence Division', 'market', gen_random_uuid());

-- Insert demo email campaigns  
INSERT INTO email_campaigns (name, subject, content, status, recipient_count, sent_count, opened_count, clicked_count, scheduled_at, user_id, template_id) VALUES
('Q3 Market Domination Campaign', 'Your Competition is Vulnerable - Strike Now', 'Limited time offer to capitalize on competitor weaknesses. 40% discount for switchers.', 'active', 2500, 2500, 875, 234, '2024-07-16 09:00:00'::timestamp, gen_random_uuid(), (SELECT id FROM email_templates LIMIT 1)),
('TechCorp Customer Acquisition', 'Better Solutions Available - Escape TechCorp Limitations', 'Targeted campaign to convert frustrated TechCorp customers to our platform.', 'completed', 1200, 1200, 456, 89, '2024-07-10 14:00:00'::timestamp, gen_random_uuid(), (SELECT id FROM email_templates LIMIT 1)),
('Stealth Intelligence Newsletter', 'Weekly Market Intelligence Briefing', 'Confidential market insights and competitor vulnerability analysis.', 'active', 850, 750, 412, 156, '2024-07-15 08:00:00'::timestamp, gen_random_uuid(), (SELECT id FROM email_templates LIMIT 1)),
('Emergency Response: DataSolutions Breach', 'Security Alert: Competitor Data Breach Detected', 'Immediate response to capitalize on DataSolutions security incident.', 'completed', 3200, 3200, 1456, 678, '2024-07-12 16:30:00'::timestamp, gen_random_uuid(), (SELECT id FROM email_templates LIMIT 1)),
('LinkedIn Disruption Campaign', 'Professional Network Influence Operation', 'Coordinated LinkedIn campaign to shift professional opinion.', 'scheduled', 1800, 0, 0, 0, '2024-07-20 10:00:00'::timestamp, gen_random_uuid(), (SELECT id FROM email_templates LIMIT 1));

-- Insert demo social media posts
INSERT INTO social_posts (platform, content, status, scheduled_at, published_at, user_id, engagement_metrics, media_urls) VALUES
('twitter', 'Just analyzed the latest market data - companies using outdated solutions are losing 23% more customers than those who upgraded. 📊 #MarketIntel #CompetitiveAdvantage', 'published', '2024-07-16 10:00:00'::timestamp, '2024-07-16 10:00:00'::timestamp, gen_random_uuid(), '{"likes": 156, "retweets": 43, "comments": 28, "impressions": 12500}', ARRAY['https://example.com/chart1.jpg']),
('linkedin', 'Industry Report: 67% of enterprise clients are reconsidering their current vendor relationships due to recent security concerns. Is your solution future-ready? 🔒', 'published', '2024-07-15 14:30:00'::timestamp, '2024-07-15 14:30:00'::timestamp, gen_random_uuid(), '{"likes": 234, "shares": 67, "comments": 45, "impressions": 18900}', NULL),
('facebook', 'Breaking: Major tech company experiences 15% customer satisfaction drop this quarter. Smart businesses are already making the switch to more reliable solutions. 💼', 'published', '2024-07-14 09:15:00'::timestamp, '2024-07-14 09:15:00'::timestamp, gen_random_uuid(), '{"likes": 89, "shares": 23, "comments": 12, "impressions": 8700}', NULL),
('instagram', 'When your competitor''s downtime becomes your uptime opportunity 📈✨ #BusinessGrowth #MarketDomination', 'published', '2024-07-13 16:45:00'::timestamp, '2024-07-13 16:45:00'::timestamp, gen_random_uuid(), '{"likes": 445, "comments": 34, "saves": 67, "impressions": 15600}', ARRAY['https://example.com/growth-chart.jpg']),
('youtube', 'NEW VIDEO: "5 Signs Your Competitor is Vulnerable (And How to Capitalize)" - Link in bio! 🎯', 'published', '2024-07-12 11:00:00'::timestamp, '2024-07-12 11:00:00'::timestamp, gen_random_uuid(), '{"views": 2340, "likes": 167, "comments": 43, "shares": 29}', ARRAY['https://example.com/video-thumbnail.jpg']),
('tiktok', 'POV: You''re watching your competitor''s market share decline while yours grows 📊💪 #BusinessTok #MarketStrategy', 'published', '2024-07-11 13:20:00'::timestamp, '2024-07-11 13:20:00'::timestamp, gen_random_uuid(), '{"views": 8900, "likes": 567, "comments": 89, "shares": 234}', NULL),
('twitter', 'THREAD: How we increased our market share by 12% in 30 days by analyzing competitor weaknesses 🧵👇', 'scheduled', '2024-07-18 15:00:00'::timestamp, NULL, gen_random_uuid(), '{}', NULL),
('linkedin', 'Exclusive whitepaper: "The Art of Competitive Intelligence in 2024" - Download before your competitors do 📋', 'scheduled', '2024-07-19 09:30:00'::timestamp, NULL, gen_random_uuid(), '{}', ARRAY['https://example.com/whitepaper-preview.jpg']),
('facebook', 'This week in competitor intel: 3 major players showed vulnerability, 2 new startups entered the market, 1 company pivoted strategy. Stay informed! 📰', 'draft', NULL, NULL, gen_random_uuid(), '{}', NULL),
('instagram', 'Behind the scenes: How our AI analyzes 10,000+ competitor data points daily 🤖✨ #TechLife #AI', 'draft', NULL, NULL, gen_random_uuid(), '{}', ARRAY['https://example.com/ai-dashboard.jpg']);

-- Insert demo appointments
INSERT INTO appointments (title, description, start_time, end_time, location, meeting_link, status, user_id) VALUES
('TechCorp Intelligence Briefing', 'Weekly strategic review of TechCorp activities and vulnerabilities', '2024-07-18 09:00:00'::timestamp, '2024-07-18 10:00:00'::timestamp, 'Conference Room Alpha', 'https://meet.google.com/abc-defg-hij', 'scheduled', gen_random_uuid()),
('DataSolutions Surveillance Review', 'Quarterly assessment of DataSolutions market position and customer sentiment', '2024-07-19 14:00:00'::timestamp, '2024-07-19 15:30:00'::timestamp, 'Virtual - Secure Channel', 'https://zoom.us/j/123456789', 'scheduled', gen_random_uuid()),
('Campaign Strategy Session', 'Planning next phase of competitive disruption campaigns', '2024-07-20 10:30:00'::timestamp, '2024-07-20 12:00:00'::timestamp, 'War Room', NULL, 'scheduled', gen_random_uuid()),
('Client Acquisition Target Meeting', 'Strategy session for converting CloudInnovate customers', '2024-07-22 13:00:00'::timestamp, '2024-07-22 14:00:00'::timestamp, 'Conference Room Beta', 'https://teams.microsoft.com/meet/xyz', 'scheduled', gen_random_uuid()),
('Weekly Intelligence Sync', 'Team synchronization on competitor monitoring and threat assessment', '2024-07-23 11:00:00'::timestamp, '2024-07-23 12:00:00'::timestamp, 'Virtual - Operations Center', 'https://meet.google.com/klm-nopq-rst', 'scheduled', gen_random_uuid()),
('Market Disruption Planning', 'Strategic planning for Q4 market disruption initiatives', '2024-07-25 15:00:00'::timestamp, '2024-07-25 17:00:00'::timestamp, 'Executive Boardroom', NULL, 'scheduled', gen_random_uuid()),
('Competitive Analysis Deep Dive', 'Comprehensive review of new market entrants and their threat level', '2024-07-26 09:30:00'::timestamp, '2024-07-26 11:00:00'::timestamp, 'Analysis Lab', 'https://zoom.us/j/987654321', 'scheduled', gen_random_uuid()),
('StartupX Threat Assessment', 'Emergency briefing on StartupX funding and strategic implications', '2024-07-17 16:00:00'::timestamp, '2024-07-17 17:00:00'::timestamp, 'Secure Communications Room', NULL, 'completed', gen_random_uuid()),
('Customer Intelligence Briefing', 'Review of customer acquisition from competitor defections', '2024-07-15 08:00:00'::timestamp, '2024-07-15 09:30:00'::timestamp, 'Intelligence Hub', 'https://meet.google.com/uvw-xyz-123', 'completed', gen_random_uuid()),
('Social Media Warfare Training', 'Advanced techniques for competitive social media campaigns', '2024-07-24 14:30:00'::timestamp, '2024-07-24 16:30:00'::timestamp, 'Training Center', NULL, 'scheduled', gen_random_uuid());