// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gifzytiilztglnvescqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpZnp5dGlpbHp0Z2xudmVzY3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzUyMzksImV4cCI6MjA2Nzk1MTIzOX0.GX6j15M945_zdLJexC-DjKlNfRAe75C-h4Bb9AgtQXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});